SAS.WEB/Models/SkillSetViewModel.cs
using System.Collections.Generic;

namespace SAS.WEB.Models
{
    public class SkillSetViewModel
    {
        public IEnumerable<CategoryViewModel> Categories { get; set; }
    }
}

SAS.WEB/Controllers/SkillSetController.cs
using SAS.BLL.Interfaces;
using SAS.WEB.Mapping;
using SAS.WEB.Models;
using SAS.WEB.Util;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace SAS.WEB.Controllers
{
    [Authorize]
    public class SkillSetController : Controller
    {
        IServiceBag serviceBag;
        ModelBuilder modelBuilder;
        
        public SkillSetController(IServiceBag ServiceBag)
        {
            serviceBag = ServiceBag;
            modelBuilder = new ModelBuilder(ServiceBag);
        }

        [HttpGet]
        public async Task<ActionResult> EditSkillSet()
        {
            var model = await modelBuilder.ObtainSkillSetVievModel(HttpContext.GetOwinContext().Authentication.User.Identity.Name);
            if (model == null)
                return new HttpNotFoundResult();
            return View(model);
        }      

        [HttpPost]
        public async Task<ActionResult> EditSkillSet(int[] skills, int[] grades)
        {
            string userName = HttpContext.GetOwinContext().Authentication.User.Identity.Name;
            var skillGrades = PositiveSkillGradesRetriver.Retrive(skills, grades);
            var skillSet = ComplexMapper.Map(new SkillSetModel() { UserName = userName, SkillGrades = skillGrades });
            var opDet = await serviceBag.SkillSetService.UpdateSkillSet(skillSet);
            if (!opDet.Succeeded)
            {
                ViewBag.Massage = opDet.Message;
                return View("Unsuccessful");
            }    
            return Redirect("/SkillSet/SkillSet");
        }      

        [HttpGet]
        public async Task<ActionResult> SkillSet()
        {
            var model = await modelBuilder.ObtainSkillSetVievModel(HttpContext.GetOwinContext().Authentication.User.Identity.Name);
            if(model == null)
                return new HttpNotFoundResult();
            if(model.Categories.Where(c => c.ContainsPositiveSkillGrades).Count() == 0)
                return Redirect("/SkillSet/EditSkillSet");
            return View(model);
        }

        protected override void Dispose(bool disposing)
        {
            serviceBag.Dispose();
            base.Dispose(disposing);
        }
    }
}

SAS.WEB/Views/SkillSet/EditSkillSet.cshtml
@using SAS.WEB.Models;
@model SkillSetViewModel
<div class="container">
    <h3>Edit skill set</h3>
    <div class="row">
        <div class="col-md-6">
            @using (Html.BeginForm("EditSkillSet", "SkillSet", FormMethod.Post))
            {
                @SkillList.SkillListFor(Model)
                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Submit" class="btn btn-default" />
                    </div>
                </div>
            }
        </div>
        <div class="col-md-6">
            <div class="panel panel-default">
                <div class="panel-heading">Skill level description</div>
                <select id="description" align="right">
                    <option value="0">Choose your level</option>
                    <option value="1" data-html="Beginner">Beginner</option>
                    <option value="2" data-html="Intermediate">Intermediate</option>
                    <option value="3" data-html="Advanced">Advanced</option>
                    <option value="4" data-html="Expert">Expert</option>
                </select>
                <div class="rateit" data-rateit-backingfld="#description"></div>
                <div>
                    <span id="rateddescr"></span>
                </div>
                <script type="text/javascript">
                    $("#description").bind('rated', function (event, value) { $('#rateddescr').text('You\'ve rated it: ' + value); });
                </script>
            </div>
        </div>
    </div>
</div>     

SAS.WEB/Views/SkillSet/SkillSet.cshtml
@using SAS.WEB.Models
@model SkillSetViewModel

<div class="contaner">
    <h3>Skill set</h3>
    <div class="row">
        <div class="col-md-6">
            <div class="panel panel-default">
                <div class="panel-body">
                    @SkillList.PositiveSkillListFor(Model)
                    @if (Model.Categories.Where(c => c.ContainsPositiveSkillGrades == true).Count() == 0)
                    {
                        <p>You have not rate your skills yet. Click <b><span class="fa fa-wrench"></span> Edit</b> to rate your skills!</p>
                    }
                </div>
            </div>
            <p><a class="btn btn-default" href="@Url.Action("EditSkillSet", "SkillSet")"><span class="fa fa-wrench"></span> Edit</a></p>
        </div>
    </div>
</div>

SAS.WEB/Views/SkillSet/Unsuccessful.cshtml
@{
    ViewBag.Title = "Unsuccessful";
}

<h4>Unfortunately, something went wrong and your skill set has not been updated. Please, try again later or contact our technical support service.</h4>
<div class="row">
    <div class="col-md-3">
        <p><a class="btn btn-default" href="@Url.Action("Contact", "Home")">Contact</a></p>
    </div>
    <div class="col-md-3">
        <p><a class="btn btn-default" href="@Url.Action("SkillSet", "SkillSet")">Back to skill set</a></p>
    </div>
</div>

@if (Request.IsAuthenticated && User.IsInRole("administrator"))
{
    <p>@ViewBag.Massage</p>
}