SAS.WEB/Controllers/RequestController.cs
using SAS.BLL.Interfaces;
using SAS.WEB.Mapping;
using SAS.WEB.Models;
using SAS.WEB.Util;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace SAS.WEB.Controllers
{
    [Authorize]
    public class RequestController : Controller
    {
        IServiceBag serviceBag;
        ModelBuilder modelBuilder;
        
        public RequestController(IServiceBag ServiceBag)
        {
            serviceBag = ServiceBag;
            modelBuilder = new ModelBuilder(ServiceBag);           
        }

        [HttpGet]
        public ActionResult CreateRequest()
        {
            var model = new RequestViewModel();
            model.Request = modelBuilder.ObtainSkillSetVievModel();
            if (model == null)
                return new HttpNotFoundResult();
            return View(model);
        }

        [HttpPost]
        public async Task<ActionResult> CreateRequest(RequestViewModel model, int[] skills, int[] grades)
        {
            if (ModelState.IsValid)
            {
                string userName = HttpContext.GetOwinContext().Authentication.User.Identity.Name;
                var skillRequirements = PositiveSkillGradesRetriver.Retrive(skills, grades);
                var requestDTO = ComplexMapper.Map(new RequestModel() { UserName = userName, Name = model.Name, SkillRequirements = skillRequirements.ToList() });
                var operationDetails = await serviceBag.RequestService.Create(requestDTO);
              
                if (operationDetails.Succeeded)
                {
                    return Redirect("/Request/RequestByName/?requestName=" + operationDetails.Property);
                }
                else
                {
                    ModelState.AddModelError(operationDetails.Property, operationDetails.Message);
                }
            }
            model.Request = await modelBuilder.ObtainSkillSetVievModel(HttpContext.GetOwinContext().Authentication.User.Identity.Name);
            // to do: provide saving of grades in case of error
            return View(model);
        }

        [HttpGet]
        public async Task<ActionResult> Requests()
        {
            string userName = HttpContext.GetOwinContext().Authentication.User.Identity.Name;
            var model = MapperBag.RequestViewMapper.Map(await serviceBag.RequestService.Find(userName));
            return View(model);
        }

        [HttpGet]
        public async Task<ActionResult> RequestByName(string requestName, int? page)
        {
            if (!(requestName == null))
            {
                string userName = HttpContext.GetOwinContext().Authentication.User.Identity.Name;
                var model = await modelBuilder.ObtainRequestViewModel(userName, requestName, (page ?? 1));
                if (!(model == null))
                    return View(model);
            }
            return new HttpNotFoundResult();           
        }

        [HttpGet]
        public async Task<ActionResult> DeleteRequestByName(string requestName)
        {
            if (!(requestName == null))
            {
                string userName = HttpContext.GetOwinContext().Authentication.User.Identity.Name;
                var model = await modelBuilder.ObtainRequestViewModel(userName, requestName, 1);
                if (!(model == null))
                    return View(model);
            }
            return new HttpNotFoundResult();
        }

        [HttpPost, ActionName("DeleteRequestByName")]
        public async Task<ActionResult> DeleteRequestByNameConfirmed(string requestName)
        {
            if (!(requestName == null))
            {
                string userName = HttpContext.GetOwinContext().Authentication.User.Identity.Name;
                var requestDTO = ComplexMapper.Map(new RequestModel() { UserName = userName, Name = requestName });
                var operationDetails = await serviceBag.RequestService.Delete(requestDTO);
                if (operationDetails.Succeeded)
                    return Redirect("/Request/Requests");
                else
                    ViewBag.Massage = operationDetails.Message;
            }
            return View("Unsuccessful");      
        }

        [HttpGet]
        public ActionResult DeleteAllRequests()
        {
            return View();
        }

        [HttpPost, ActionName("DeleteAllRequests")]
        public async Task<ActionResult> DeleteAllRequestsConfirmed()
        {
            string userName = HttpContext.GetOwinContext().Authentication.User.Identity.Name;           
            var operationDetails = await serviceBag.RequestService.DeleteAll(userName);
            if (operationDetails.Succeeded)
                return Redirect("/Request/Requests");
            ViewBag.Massage = operationDetails.Message;
            return View("Unsuccessful");
        }

        protected override void Dispose(bool disposing)
        {
            serviceBag.Dispose();
            base.Dispose(disposing);
        }
    }
}

SAS.WEB/Controllers/ToolsController.cs
using PagedList;
using SAS.BLL.Interfaces;
using SAS.BLL.Services;
using SAS.WEB.Mapping;
using SAS.WEB.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SAS.WEB.Controllers
{
    [Authorize(Roles = "manager, administrator")]
    public class ToolsController : Controller
    {
        IServiceBag serviceBag;

        public ToolsController(IServiceBag ServiceBag)
        {
            serviceBag = ServiceBag;
        }

        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        [Authorize(Roles = "manager")]
        public ActionResult CreateCategory()
        {
            return View();
        }

        [HttpPost]
        [Authorize(Roles = "manager")]
        public ActionResult CreateCategory(CategoryModel model)
        {
            if (ModelState.IsValid)
            {
                var cat = MapperBag.CategoryMapper.Map(model);
                var operationDetails = serviceBag.CategoryService.Create(cat);
                if (operationDetails.Succeeded)
                {
                    ViewBag.Item = "Category";
                    ViewBag.State = "created";
                    return View("Successful");
                }
                else
                {
                    ModelState.AddModelError(operationDetails.Property, operationDetails.Message);
                }
            }            
            return View(model);
        }

        [HttpGet]
        [Authorize(Roles = "manager")]
        public ActionResult CreateSkill()
        {
            ViewBag.Categories = MapperBag.CategoryMapper.Map(serviceBag.CategoryService.GetAll());
            return View();
        }

        [HttpPost]
        [Authorize(Roles = "manager")]
        public ActionResult CreateSkill(SkillModel model)
        {
            if (ModelState.IsValid)
            {
                var skill = MapperBag.SkillMapper.Map(model);
                var operationDetails = serviceBag.SkillService.Create(skill);
                if (operationDetails.Succeeded)
                {
                    ViewBag.Item = "Skill";
                    ViewBag.State = "created";
                    return View("Successful");
                }
                else
                {
                    ModelState.AddModelError(operationDetails.Property, operationDetails.Message);
                }
            }
            ViewBag.Categories = MapperBag.CategoryMapper.Map(serviceBag.CategoryService.GetAll());
            return View(model);
        }

        protected override void Dispose(bool disposing)
        {
            serviceBag.Dispose();
            base.Dispose(disposing);
        }

        [HttpGet]
        [Authorize(Roles = "administrator")]
        public ActionResult AllUsers(int? page)
        {
            var users = MapperBag.UserMapper.Map(serviceBag.UserService.GetAll());
            var model = users.ToPagedList(page ?? 1, 10);
            return View(model);
        }

        [HttpGet]
        [Authorize(Roles = "administrator")]
        public ActionResult EditUser(string userName)
        {
            var model = MapperBag.UserMapper.Map(serviceBag.UserService.Find(userName));

            return View(model);
        }

        [HttpPost]
        [Authorize(Roles = "administrator")]
        public ActionResult EditUser(UserModel user)
        {
            if (user == null)
                return new HttpNotFoundResult();
            if (ModelState.IsValid)
            {
                var operationDetails = serviceBag.UserService.UpdateRoles(MapperBag.UserMapper.Map(user));
                if(operationDetails.Succeeded)
                {
                    ViewBag.Item = "User";
                    ViewBag.State = "updated";
                    return View("Successful");
                }
                ModelState.AddModelError(operationDetails.Property, operationDetails.Message);
            }                                  
            return View(user);
        }
    }
}

SAS.WEB/Views/Shared/_Layout.cshtml
@using Microsoft.AspNet.Identity
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Skill Accounting System" />
    <title>@ViewBag.Title - Skill Accounting System</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/rateit.css" rel="stylesheet" type="text/css" />
    <link href='@Url.Content("~/Content/themes/base/all.css")' rel="stylesheet" type="text/css" />
    <script src='@Url.Content("~/Scripts/jquery-ui-1.12.1.min.js")' type="text/javascript"></script>
    <script src='@Url.Content("~/Scripts/jquery.rateit.min.js")' type="text/javascript"></script>
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
    <link rel="stylesheet" href="http://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.6.3/css/font-awesome.min.css">
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Skill Accounting System", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a href="@Url.Action("Index", "Home")"><span class="fa fa-home"></span> Home</a></li>
                    @if (Request.IsAuthenticated && User.IsInRole("user"))
                    {
                        <li><a href="@Url.Action("UserProfile", "UserProfile")"><span class="fa fa-user"></span> Profile</a></li>
                        <li><a href="@Url.Action("SkillSet", "SkillSet")"><span class="fa fa-star-half-o"></span> Skill set</a></li>
                        <li><a href="@Url.Action("CreateRequest", "Request")"><span class="fa fa fa-search"></span> New request</a></li>
                        <li><a href="@Url.Action("Requests", "Request")"><span class="fa fa fa-history "></span> Search history</a></li>
                    }
                    @if (Request.IsAuthenticated && (User.IsInRole("manager") || User.IsInRole("administrator")))
                    {
                        <li><a href="@Url.Action("Index", "Tools")"><span class="fa fa fa-wrench"></span> Tools</a></li>
                    }
                </ul>

                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Skill Accounting System - Dmytro Heorhin</p>
        </footer>
    </div>
    <script src="~/Scripts/jquery-3.1.0.min.js"></script>
    <script src="~/Scripts/jquery.rateit.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>